name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop, feature/*]

jobs:
  run-tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4.0'

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Install Dependencies
        run: swift package resolve

      - name: Build and Run Tests
        run: |
          xcodebuild -scheme SwiftUIFlutterLikeForm test -destination "platform=iOS Simulator,name=iPhone 16,OS=18.5"
