name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop, feature/*]
jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run SwiftFormat
        run: |
          brew install swiftformat
          swiftformat --lint --path .

      - name: Test      
        run: |
          swift test

